version: '3'
services:
    php-fpm:
        build:
            context: .
            dockerfile: ./php-fpm/Dockerfile
        #image: app:latest2
        volumes:
            - ./logs:/var/log/php
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./source:/var/www/html
        working_dir: /var/www/html
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - php-fpm
        #image: web:latest2
        ports:
            - 80:80
        volumes:
            - ./logs:/var/log/nginx
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=${TZ:-Asia/Tokyo}
